-- AlterTable
ALTER TABLE `cutOffPeriod` ADD COLUMN `isClosing` TINYINT NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `payslipHeader` ADD COLUMN `absent` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `paidLeave` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `sick` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `unpaidLeave` TINYINT NOT NULL DEFAULT 0;
